Repository Antares-Network/AntaresBot, pull requests merged in 2021-04, with the labels that each got.

#77 Apply DeepScan recommended changes
  .deepsource.toml
  .github/workflows/node.js.yml
  README.md
  actions/guildBan.js
  actions/moderate.js
  actions/onReady.js
  commands/owner/botBanGuild.js
  commands/owner/botBanOwner.js
  commands/owner/botBanUser.js
  commands/owner/botUnbanGuild.js
  commands/owner/botUnbanOwner.js
  commands/owner/botUnbanUser.js
  commands/user/diceroll.js
  functions/channelCheck.js
  index.js
  package.json
Labels: Align branch, bug fix

#99 Align branches
  .github/workflows/codeql-analysis.yml
  .github/workflows/main.yml
Labels: Align branch

#101 Added globals
  package.json
Labels: bug fix

#100 Update to version 1.3.19
  .jshintrc
  Discarded commands/ip.js
  actions/docCreate.js
  actions/gateCreate.js
  actions/guildUpdate.js
  actions/logToConsole.js
  actions/onReady.js
  actions/piiCreate.js
  commands/admin/adminHelp.js
  commands/admin/counting.js
  commands/admin/pollCreate.js
  commands/antares/mcuser.js
  commands/owner/adminMSG.js
  commands/owner/botBanOwner.js
  commands/owner/botUnbanOwner.js
  commands/owner/guildMsg.js
  commands/owner/ignore.js
  commands/owner/leave.js
  commands/owner/me.js
  commands/owner/serverlist.js
  commands/owner/whois.js
  commands/user/8ball.js
  commands/user/cat.js
  commands/user/coinflip.js
  commands/user/diceroll.js
  commands/user/dog.js
  commands/user/github.js
  commands/user/help.js
  commands/user/invite.js
  commands/user/ping.js
  commands/user/privacy.js
  commands/user/random.js
  commands/user/reddit.js
  commands/user/stats.js
  commands/user/suggest.js
  commands/user/update.js
  commands/user/uptime.js
  functions/channelCheck.js
  functions/counting.js
  index.js
  package-lock.json
  package.json
  resources/antaresDiscordIcon.png
  test.js
Labels: HOTFIX, REWRITE, bug fix

#105 Update version to 1.3.20 -- Oops
  index.js
  package-lock.json
  package.json
Labels: Minor version update
